version: "3"

services:
  server:
    image: &image-nim nimlang/nim:1.0.6-ubuntu
    restart: on-failure
    environment: &app-env
      PORT: '4001'
      DB_HOST: db
      DB_PORT: '27017'
      DB_DBNAME: nimbot
      DB_USER: writer
      DB_PASSWORD: password
    volumes:
      - "./nimbot_server:/work"
      - "./entrypoint.sh:/entrypoint.sh"
      - "./volume/server/cache:/root/.cache/nim"
      - "./volume/server/nimble:/root/.nimble"
    working_dir: /work
    ports:
      - 4001:4001
    depends_on:
      - db
      - executor
      - fluentd
    logging: &logging
      driver: "fluentd"
      options:
        fluentd-address: "localhost:24224"
        tag: "docker.{{.Name}}"
    entrypoint: "/entrypoint.sh nimbot_server"

  executor:
    image: *image-nim
    restart: on-failure
    environment:
      <<: *app-env
      SLACK_URL: "http://slack_mock"
    volumes:
      - "./nimbot_executor:/work"
      - "./entrypoint.sh:/entrypoint.sh"
      - "./volume/executor/cache:/root/.cache/nim"
      - "./volume/executor/nimble:/root/.nimble"
    working_dir: /work
    depends_on:
      - db
      - slack_mock
      - fluentd
    entrypoint: "/entrypoint.sh nimbot_executor"
    logging: *logging

  db:
    image: mongo:3.6
    restart: on-failure
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: nimbot
    expose:
      - "27017"
    ports:
      - 27017:27017
    volumes:
      - ./volume/db/db:/data/db
      - ./volume/db/configdb:/data/configdb
      - ./volume/db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/
    logging: *logging
    depends_on:
      - fluentd

  slack_mock:
    image: nginx:1.17
    expose:
      - "80"
      - "443"
    logging: *logging
    depends_on:
      - fluentd

  fluentd:
    image: fluentd:v1.9-1
    ports:
      - 24224:24224
      - 24224:24224/udp
    # expose:
    #   - 24224
    volumes:
      - "./volume/fluentd/log:/fluentd/log"
