version: "3"

services:
  server:
    image: &image-nim nimlang/nim:1.0.6-ubuntu
    environment:
      NIMBOT_SERVER_PORT: '4001'
      NIMBOT_SERVER_DB_HOST: db
      NIMBOT_SERVER_DB_PORT: '27017'
      NIMBOT_SERVER_DB_DBNAME: nimbot
      NIMBOT_SERVER_DB_USER: writer
      NIMBOT_SERVER_DB_PASSWORD: password
    volumes:
      - ".:/work"
      - "./volume/server/cache:/root/.cache/nim"
      - "./volume/server/nimble:/root/.nimble"
    working_dir: /work
    ports:
      - 4001:4001
    depends_on:
      - db
      - executor
    entrypoint: "./entrypoint.sh nimbot_server"

  executor:
    image: *image-nim
    environment:
      NIMBOT_EXECUTOR_PORT: '4001'
      NIMBOT_EXECUTOR_DB_HOST: db
      NIMBOT_EXECUTOR_DB_PORT: '27017'
      NIMBOT_EXECUTOR_DB_DBNAME: nimbot
      NIMBOT_EXECUTOR_DB_USER: writer
      NIMBOT_EXECUTOR_DB_PASSWORD: password
    volumes:
      - ".:/work"
      - "./volume/executor/cache:/root/.cache/nim"
      - "./volume/executor/nimble:/root/.nimble"
    working_dir: /work
    depends_on:
      - db
    entrypoint: "./entrypoint.sh nimbot_executor"

  db:
    image: mongo:3.6
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: nimbot
    expose:
      - "27017"
    ports:
      - 27017:27017
    volumes:
      - ./volume/db/db:/data/db
      - ./volume/db/configdb:/data/configdb
      - ./volume/db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/
