version: "3.7"

services:
  # Server
  server:
    image: nimlang/nim:1.0.6-ubuntu
    restart: on-failure
    environment: &app-env
      PORT: '4001'
      DB_HOST: mongodb
      DB_PORT: '27017'
      DB_DBNAME: nimbot
      DB_USER: writer
      DB_PASSWORD: password
    volumes:
      - "./nimbot_server:/work"
      - "./entrypoint.sh:/entrypoint.sh"
      - "./volume/server/cache:/root/.cache/nim"
      - "./volume/server/nimble:/root/.nimble"
    working_dir: /work
    ports:
      - 4001:4001
    depends_on:
      - mongodb
      - executor
    entrypoint: "/entrypoint.sh nimbot_server"

  # Executor
  executor:
    build:
      context: ./build/executor
      dockerfile: Dockerfile
      target: base
    image: jiro4989/nimbot/executor
    restart: on-failure
    environment:
      <<: *app-env
      SLACK_URL: "http://slack_mock"
    volumes:
      - "./nimbot_executor:/work"
      - "./entrypoint.sh:/entrypoint.sh"
      - "./volume/executor/cache:/root/.cache/nim"
      - "./volume/executor/nimble:/root/.nimble"
      - "/var/run/docker.sock:/var/run/docker.sock" # docker out of docker
    working_dir: /work
    depends_on:
      - mongodb
      - slack_mock
    entrypoint: "/entrypoint.sh nimbot_executor"

  mongodb:
    image: mongo:3.6
    restart: on-failure
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: nimbot
    expose:
      - "27017"
    ports:
      - 27017:27017
    volumes:
      - ./conf/mongodb/init.sh:/docker-entrypoint-initdb.d/init.sh

  slack_mock:
    image: nginx:1.17
    expose:
      - "80"
      - "443"
