version: "3.7"

services:
  server:
    image: jiro4989/nimbot:server-runtime
    environment: &app-env
      DB_PASSWORD: "$DB_PASSWORD"
    depends_on:
      - db
      - executor
      - fluentd
    entrypoint: "/usr/local/bin/nimbot_server"

  executor:
    image: jiro4989/nimbot:executor-runtime
    environment:
      <<: *app-env
      SLACK_URL: "$SLACK_URL"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock" # docker out of docker
    depends_on:
      - db
      - fluentd
    entrypoint: "/usr/local/bin/nimbot_executor"

  db:
    image: mongo:3.6
    restart: on-failure
    environment:
      MONGO_INITDB_ROOT_PASSWORD: "$ROOT_PASSWORD"
    volumes:
      - /var/lib/nimbot/db:/data/db
      - /var/lib/nimbot/configdb:/data/configdb
    depends_on:
      - fluentd

  fluentd:
    image: jiro4989/nimbot:fluentd-runtime
    ports:
      - 24224:24224
      - 24224:24224/udp
    volumes:
      - "/var/log/nimbot:/fluentd/log"
