version: "3.7"

services:

  mongodb:
    image: mongo:3.6
    restart: on-failure
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: nimbot
    expose:
      - "27017"
    ports:
      - 27017:27017
    volumes:
      # NOTE: 毎回作り直せばいいからvolumeしない
      # - ./volume/db/db:/data/db
      # - ./volume/db/configdb:/data/configdb
      - ../../conf/mongodb/init.js:/docker-entrypoint-initdb.d/init.js
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "localhost:24224"
        tag: "log.{{.Name}}"

networks:
  fluentd_default:
    external: true
