version: "3.7"

services:

  db:
    image: mongo:3.6
    restart: on-failure
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: nimbot
    expose:
      - "27017"
    ports:
      - 27017:27017
    volumes:
      - ./volume/db/db:/data/db
      - ./volume/db/configdb:/data/configdb
      - ./volume/db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/
    networks:
      - db
      - nimbot_log
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "localhost:24224"
        tag: "log.{{.Name}}"

networks:
  db:
  nimbot_log:
    external: true
