version: "3.7"

services:
  server:
    build:
      context: ../../
      dockerfile: ./build/server/Dockerfile
      target: runtime
    image: jiro4989/nimbot:server-runtime
    restart: on-failure
    environment: &app-env
      PORT: '4001'
      DB_HOST: mongodb
      DB_PORT: '27017'
      DB_DBNAME: nimbot
      DB_USER: writer
      DB_PASSWORD: "$DB_PASSWORD"
    ports:
      - 4001:4001
    depends_on:
      - executor
    networks: &network
      - back
      - mongodb_default
    entrypoint: "/usr/local/bin/nimbot_server"

  executor:
    build:
      context: ../../
      dockerfile: ./build/executor/Dockerfile
      target: runtime
    image: jiro4989/nimbot:executor-runtime
    restart: on-failure
    environment:
      <<: *app-env
      SLACK_URL: "$SLACK_URL"
      HOST_PWD: "$PWD"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock" # docker out of docker
      - "./executor:/executor"
    networks: *network
    entrypoint: "/usr/local/bin/nimbot_executor"

  slack_mock:
    image: nginx:1.17
    container_name: slack_mock
    expose:
      - "80"
      - "443"
    networks:
      - back

networks:
  back:
  mongodb_default:
    external: true
