name: schedule-build

on:
  schedule:
    - cron: '0 1 * * *'

env:
  DOCKER_REGISTORY: jiro4989/nimbot

jobs:
  build-runtime:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag:
          - stable
          - devel
    steps:
      - uses: actions/checkout@v1
      - name: Login docker
        run: echo "${{ secrets.DOCKER_PASS }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin
      - name: Build compiler
        run: docker build --tag ${{ env.DOCKER_REGISTORY }}:compiler-${{ matrix.tag }} -f ./build/compiler_${{ matrix.tag }}/Dockerfile .
      - name: Docker push
        run: docker push ${{ env.DOCKER_REGISTORY }}:compiler-${{ matrix.tag }}
