name: build-image

on:
  push:
    paths:
      - 'Dockerfile*'

env:
  IMAGE: jiro4989/nimbot/runtime

jobs:
  skip:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Skip job"

  before:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - run: echo "no [skip ci]"

  build-runtime:
    runs-on: ubuntu-latest
    needs: before
    steps:
      - uses: actions/checkout@v1
      - name: Publish Docker
        uses: elgohr/Publish-Docker-Github-Action@2.13
        with:
          name: ${{ env.IMAGE }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          tags: latest
          if: startsWith(github.ref, 'refs/heads/master')

  build-runtime-devel:
    runs-on: ubuntu-latest
    needs: before
    steps:
      - uses: actions/checkout@v1
      - name: Publish Docker
        uses: elgohr/Publish-Docker-Github-Action@2.13
        with:
          name: ${{ env.IMAGE }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          tags: devel
          dockerfile: Dockerfile_devel
          if: startsWith(github.ref, 'refs/heads/master')
