name: build

on:
  push:
    paths-ignore:
      - 'LICENSE'
      - 'README.*'
      - '*/README.*'
      - 'docs/*'
  release:
    types: [published]

env:
  APP_NAME: nimbot
  IMAGE: jiro4989/nimbot/runtime
  DOCKER_REGISTORY: jiro4989/nimbot

jobs:
  skip:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Skip job"

  before:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - run: echo "no [skip ci]"

  build:
    runs-on: ubuntu-latest
    needs: before
    strategy:
      matrix:
        tag:
          - server
          - executor
          - fluentd
    steps:
      - uses: actions/checkout@v1
      - name: Login docker
        run: echo "${{ secrets.DOCKER_PASS }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin
      - name: Build app
        run: docker build --no-cache --tag ${{ env.DOCKER_REGISTORY }}:${{ matrix.tag }}-runtime -f ./build/${{ matrix.tag }}/Dockerfile .
      - name: Docker push
        run: docker push ${{ env.DOCKER_REGISTORY }}:${{ matrix.tag }}-runtime
        if: github.ref == 'refs/heads/master'

  create-tag-draft:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs: build
    steps:
      - uses: release-drafter/release-drafter@v5.3.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    steps:
      - name: Deploy
        run: curl -X POST -H "${{ env.HEADER }}" -d '${{ env.BODY }}' ${{ secrets.DEPLOY_URL }}
        env:
          HEADER: "Content-Type: application/json"
          BODY: '{"text": "sushi"}'
