name: test

on:
  push:
    paths-ignore:
      - 'LICENSE'
      - 'README.*'
      - '*/README.*'
      - 'docs/*'

jobs:
  skip:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Skip job"

  before:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - run: echo "no [skip ci]"

  test:
    runs-on: ubuntu-latest
    needs: before
    strategy:
      matrix:
        tag:
          - server
          - executor
    steps:
      - uses: actions/checkout@v1
      - name: Build app
        run: docker build --no-cache -f ./build/${{ matrix.tag }}/Dockerfile .
