name: release

on:
  push:
    tags:
      - 'v*.*.*'

env:
  APP_NAME: nimbot
  IMAGE: jiro4989/nimbot/runtime
  DOCKER_REGISTORY: jiro4989/nimbot

jobs:
  skip:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Skip job"

  before:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - run: echo "no [skip ci]"

  test:
    runs-on: ubuntu-latest
    needs: before
    strategy:
      matrix:
        tag:
          - server
          - executor
          - fluentd
    steps:
      - uses: actions/checkout@v1
      - name: Login docker
        run: echo "${{ secrets.DOCKER_PASS }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin
      - name: Build app
        run: docker build --no-cache --tag ${{ env.DOCKER_REGISTORY }}:${{ matrix.tag }}-runtime -f ./build/${{ matrix.tag }}/Dockerfile .
      - name: Docker push
        run: docker push ${{ env.DOCKER_REGISTORY }}:${{ matrix.tag }}-runtime

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy
        run: curl -X POST -H "${{ env.HEADER }}" -d '${{ env.BODY }}' ${{ secrets.DEPLOY_URL }}
        env:
          HEADER: "Content-Type: application/json"
          BODY: '{"text": "sushi"}'
